name: Build & Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Swift
        uses: swift-actions/setup-swift@v2.0.0
        with:
          swift-version: ${{ matrix.swift }}
      - name: Checkout Project
        uses: actions/checkout@v4
      - name: Build
        run: xcrun swift build
      - run: rm -rf reports && mkdir reports
      - name: Run tests
        run: xcrun swift test --parallel --xunit-output "reports/test-result.xml"
      - name: Test Report
        uses: dorny/test-reporter@v1.9.1
        if: success() || failure()
        with:
          name: Test Results
          path: reports/test-result.xml
          reporter: swift-xunit
